# Generated by Django 3.2 on 2023-05-22 17:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('core', '0001_initial'),
	]

	operations = [
		migrations.AddField(
			model_name='user',
			name='recovery_codes',
			field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, null=True, size=None, verbose_name='Recovery Codes'),
		),
	]
