# Generated by Django 3.2 on 2022-07-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('notes', models.TextField(blank=True, null=True)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('value', models.CharField(max_length=256, verbose_name='value')),
                ('type', models.CharField(choices=[('STR', 'string'), ('LI', 'list'), ('BOOL', 'boolean'), ('OBJ', 'object'), ('TUP', 'tuple')], max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
