# Generated by Django 5.1.7 on 2025-05-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ldapsetting",
            name="name",
            field=models.CharField(
                choices=[
                    ("LDAP_AUTH_URL", "LDAP_AUTH_URL"),
                    ("LDAP_DOMAIN", "LDAP_DOMAIN"),
                    ("LDAP_LOG_MAX", "LDAP_LOG_MAX"),
                    ("LDAP_LOG_READ", "LDAP_LOG_READ"),
                    ("LDAP_LOG_CREATE", "LDAP_LOG_CREATE"),
                    ("LDAP_LOG_UPDATE", "LDAP_LOG_UPDATE"),
                    ("LDAP_LOG_DELETE", "LDAP_LOG_DELETE"),
                    ("LDAP_LOG_OPEN_CONNECTION", "LDAP_LOG_OPEN_CONNECTION"),
                    ("LDAP_LOG_CLOSE_CONNECTION", "LDAP_LOG_CLOSE_CONNECTION"),
                    ("LDAP_LOG_LOGIN", "LDAP_LOG_LOGIN"),
                    ("LDAP_LOG_LOGOUT", "LDAP_LOG_LOGOUT"),
                    ("LDAP_AUTH_USE_SSL", "LDAP_AUTH_USE_SSL"),
                    ("LDAP_AUTH_USE_TLS", "LDAP_AUTH_USE_TLS"),
                    ("LDAP_AUTH_TLS_VERSION", "LDAP_AUTH_TLS_VERSION"),
                    ("LDAP_AUTH_SEARCH_BASE", "LDAP_AUTH_SEARCH_BASE"),
                    ("LDAP_DNS_LEGACY", "LDAP_DNS_LEGACY"),
                    ("LDAP_AUTH_OBJECT_CLASS", "LDAP_AUTH_OBJECT_CLASS"),
                    ("EXCLUDE_COMPUTER_ACCOUNTS", "EXCLUDE_COMPUTER_ACCOUNTS"),
                    ("LDAP_AUTH_USER_FIELDS", "LDAP_AUTH_USER_FIELDS"),
                    (
                        "LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN",
                        "LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN",
                    ),
                    ("LDAP_AUTH_CONNECTION_USER_DN", "LDAP_AUTH_CONNECTION_USER_DN"),
                    ("LDAP_AUTH_CONNECTION_USERNAME", "LDAP_AUTH_CONNECTION_USERNAME"),
                    ("LDAP_AUTH_CONNECTION_PASSWORD", "LDAP_AUTH_CONNECTION_PASSWORD"),
                    ("LDAP_AUTH_CONNECT_TIMEOUT", "LDAP_AUTH_CONNECT_TIMEOUT"),
                    ("LDAP_AUTH_RECEIVE_TIMEOUT", "LDAP_AUTH_RECEIVE_TIMEOUT"),
                    ("ADMIN_GROUP_TO_SEARCH", "ADMIN_GROUP_TO_SEARCH"),
                ],
                max_length=128,
                verbose_name="name",
            ),
        ),
    ]
