# Generated by Django 5.1.7 on 2025-06-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("core", "0001_initial"),
	]

	operations = [
		migrations.AlterField(
			model_name="log",
			name="log_target_class",
			field=models.CharField(
				choices=[
					("USER", "User"),
					("GROUP", "Group"),
					("SSO_APP", "SSO Application"),
					("SSO_CLIENT", "SSO Client"),
					("SSO_ASG", "SSO Application Group"),
					("OU", "Organizational Unit"),
					("DOM", "Domain"),
					("GPO", "Group Policy Object"),
					("LDAP", "LDAP Object"),
					("CONN", "Connection"),
					("SET", "Setting"),
					("DNSZ", "DNS Zone"),
					("DNSR", "DNS Record"),
					("UNKNOWN", "Unknown"),
				],
				max_length=256,
				verbose_name="log_target_class",
			),
		),
	]
