# Generated by Django 3.2 on 2022-07-31 02:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='log',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='log',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='log',
            name='modified_at',
        ),
        migrations.AddField(
            model_name='log',
            name='logged_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='logged at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='rotated',
            field=models.BooleanField(default=False, verbose_name='rotated'),
        ),
        migrations.AddField(
            model_name='log',
            name='rotated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='rotated at'),
        ),
    ]
