# Generated by Django 3.2 on 2022-08-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial_D'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='logged_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='logged at'),
        ),
    ]
