# Generated by Django 5.1.7 on 2025-04-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="log",
            name="actionType",
        ),
        migrations.RemoveField(
            model_name="log",
            name="affectedObject",
        ),
        migrations.RemoveField(
            model_name="log",
            name="extraMessage",
        ),
        migrations.RemoveField(
            model_name="log",
            name="objectClass",
        ),
        migrations.AddField(
            model_name="log",
            name="log_target",
            field=models.JSONField(blank=True, null=True, verbose_name="log_target"),
        ),
        migrations.AddField(
            model_name="log",
            name="log_target_class",
            field=models.CharField(
                choices=[
                    ("USER", "User"),
                    ("GROUP", "Group"),
                    ("OU", "Organizational Unit"),
                    ("DOM", "Domain"),
                    ("GPO", "Group Policy Object"),
                    ("LDAP", "LDAP Object"),
                    ("CONN", "Connection"),
                    ("SET", "Setting"),
                    ("DNSZ", "DNS Zone"),
                    ("DNSR", "DNS Record"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="UNKNOWN",
                max_length=256,
                verbose_name="log_target_class",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="log",
            name="message",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="message"
            ),
        ),
        migrations.AddField(
            model_name="log",
            name="operation_type",
            field=models.CharField(
                choices=[
                    ("CREATE", "Create"),
                    ("READ", "Read"),
                    ("UPDATE", "Update"),
                    ("DELETE", "Delete"),
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("OPEN_CONNECTION", "Open Connection"),
                    ("CLOSE_CONNECTION", "Close Connection"),
                    ("RENAME", "Rename"),
                    ("MOVE", "Move"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="UNKNOWN",
                max_length=256,
                verbose_name="operation_type",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="log",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
