# Generated by Django 5.1.7 on 2025-07-14 16:37
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("core", "0002_add_log_classes"),
	]

	operations = [
		migrations.CreateModel(
			name="LdapRef",
			fields=[
				(
					"id",
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name="ID",
					),
				),
				(
					"created_at",
					models.DateTimeField(
						auto_now_add=True, verbose_name="created at"
					),
				),
				(
					"modified_at",
					models.DateTimeField(
						auto_now=True, verbose_name="modified at"
					),
				),
				(
					"deleted_at",
					models.DateTimeField(
						blank=True, null=True, verbose_name="deleted at"
					),
				),
				(
					"deleted",
					models.BooleanField(default=False, verbose_name="deleted"),
				),
				("notes", models.TextField(blank=True, null=True)),
				("distinguished_name", models.CharField(unique=True)),
				("object_security_id_bytes", models.BinaryField(unique=True)),
				("object_security_id", models.CharField(unique=True)),
			],
			options={
				"abstract": False,
				"db_table": "core_ldap_reference",
			},
		),
		migrations.AddField(
			model_name="applicationsecuritygroup",
			name="ldap_refs",
			field=models.ManyToManyField(
				blank=True, related_name="asg_ldap_ref", to="core.ldapref"
			),
		),
	]
