# Generated by Django 3.2 on 2022-08-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_log_logged_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='distinguishedName',
            field=models.CharField(max_length=256, null=True, unique=True, verbose_name='distinguishedName'),
        ),
    ]
