# Generated by Django 3.2 on 2022-07-31 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220731_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='rotated',
        ),
    ]
