# Generated by Django 5.1.7 on 2025-05-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("core", "0002_alter_ldapsetting_name"),
	]

	operations = [
		migrations.AddField(
			model_name="applicationsecuritygroup",
			name="uuid",
			field=models.UUIDField(default=None, editable=False),
		),
	]
