# Generated by Django 3.2 on 2022-07-21 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='encryptedPassword',
            field=models.CharField(max_length=256, null=True, verbose_name='encryptedPassword'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='type',
            field=models.CharField(choices=[('INT', 'integer'), ('FLO', 'float'), ('STR', 'string'), ('LI', 'list'), ('BOOL', 'boolean'), ('OBJ', 'object'), ('TUP', 'tuple')], max_length=256),
        ),
    ]
