# Generated by Django 5.1.7 on 2025-05-06 19:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_ldapsetting_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="dn",
        ),
    ]
