# Generated by Django 3.2 on 2022-07-31 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_log_rotated'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='willrotate',
            field=models.BooleanField(default=False, verbose_name='willrotate'),
        ),
    ]
