# Generated by Django 5.1.7 on 2025-06-11 17:32

import core.serializers.ldap
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("core", "0003_applicationsecuritygroup_uuid"),
	]

	operations = [
		migrations.AlterField(
			model_name="user",
			name="username",
			field=models.CharField(
				db_index=True,
				max_length=128,
				unique=True,
				validators=[core.serializers.ldap.ldap_user_validator_se],
				verbose_name="username",
			),
		),
	]
