# Generated by Django 5.1.7 on 2025-05-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_user_dn"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="_distinguished_name",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Distinguished Name"
            ),
        ),
    ]
