# Generated by Django 4.2.4 on 2024-03-25 17:32

from django.db import migrations

def create_default_preset(apps, schema_editor):
	LDAPPreset = apps.get_model('core', 'LDAPPreset')
	LDAPPreset.objects.create(name='default_preset', label="Default Preset", active=True)

def remove_default_preset(apps, schema_editor):
	LDAPPreset = apps.get_model('core', 'LDAPPreset')
	LDAPPreset.objects.filter(name='default').delete_permanently()

class Migration(migrations.Migration):

	dependencies = [
		('core', '0003_ldappreset_ldapsetting'),
	]

	operations = [
		migrations.RunPython(create_default_preset, remove_default_preset)
	]
