# Generated by Django 3.2 on 2022-08-06 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_distinguishedname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='distinguishedName',
        ),
    ]
