# Generated by Django 4.2.4 on 2024-03-25 21:16

import core.models.validators.ldap_uri
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ldap_preset_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldapsetting',
            name='v_bool',
            field=models.BooleanField(blank=True, null=True, verbose_name='param_v_bool'),
        ),
        migrations.AlterField(
            model_name='ldapsetting',
            name='v_integer',
            field=models.IntegerField(blank=True, null=True, verbose_name='param_v_integer'),
        ),
        migrations.AlterField(
            model_name='ldapsetting',
            name='v_json',
            field=models.JSONField(blank=True, null=True, verbose_name='param_v_json'),
        ),
        migrations.AlterField(
            model_name='ldapsetting',
            name='v_ldap_uri',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='param_v_ldap_uri'), blank=True, null=True, size=None, validators=[core.models.validators.ldap_uri.validate_ldap_uri], verbose_name='param_v_ldap_uri_list'),
        ),
        migrations.AlterField(
            model_name='ldapsetting',
            name='v_password',
            field=models.CharField(blank=True, null=True, verbose_name='param_v_password'),
        ),
        migrations.AlterField(
            model_name='ldapsetting',
            name='v_string',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='param_v_string'),
        ),
        migrations.AlterField(
            model_name='ldapsetting',
            name='v_tls',
            field=models.CharField(blank=True, null=True, verbose_name='param_v_tls'),
        ),
    ]
