# Generated by Django 3.2 on 2022-08-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_distinguishedname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='objectClass',
            field=models.CharField(choices=[('USER', 'User'), ('GROUP', 'Group'), ('OU', 'Organizational Unit'), ('DOM', 'Domain'), ('GPO', 'Group Policy Object'), ('LDAP', 'LDAP Object'), ('CONN', 'Connection'), ('SET', 'Setting'), ('DNSZ', 'DNS Zone'), ('DNSR', 'DNS Record')], max_length=256, verbose_name='objectClass'),
        ),
    ]
