# Generated by Django 5.1.7 on 2025-06-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("core", "0004_alter_user_username"),
	]

	operations = [
		migrations.AlterField(
			model_name="interlocksetting",
			name="name",
			field=models.CharField(
				choices=[
					("ILCK_AES_KEY", "ILCK_AES_KEY"),
					("ILCK_ENABLE_LDAP", "ILCK_ENABLE_LDAP"),
					("ILCK_LOG_MAX", "ILCK_LOG_MAX"),
					("ILCK_LOG_READ", "ILCK_LOG_READ"),
					("ILCK_LOG_CREATE", "ILCK_LOG_CREATE"),
					("ILCK_LOG_UPDATE", "ILCK_LOG_UPDATE"),
					("ILCK_LOG_DELETE", "ILCK_LOG_DELETE"),
					(
						"ILCK_LOG_OPEN_LDAP_CONNECTION",
						"ILCK_LOG_OPEN_LDAP_CONNECTION",
					),
					(
						"ILCK_LOG_CLOSE_LDAP_CONNECTION",
						"ILCK_LOG_CLOSE_LDAP_CONNECTION",
					),
					("ILCK_LOG_LOGIN", "ILCK_LOG_LOGIN"),
					("ILCK_LOG_LOGOUT", "ILCK_LOG_LOGOUT"),
				],
				verbose_name="type",
			),
		),
		migrations.AlterField(
			model_name="ldapsetting",
			name="name",
			field=models.CharField(
				choices=[
					("LDAP_AUTH_URL", "LDAP_AUTH_URL"),
					("LDAP_DOMAIN", "LDAP_DOMAIN"),
					("LDAP_AUTH_USE_SSL", "LDAP_AUTH_USE_SSL"),
					("LDAP_AUTH_USE_TLS", "LDAP_AUTH_USE_TLS"),
					("LDAP_AUTH_TLS_VERSION", "LDAP_AUTH_TLS_VERSION"),
					("LDAP_AUTH_SEARCH_BASE", "LDAP_AUTH_SEARCH_BASE"),
					("LDAP_DNS_LEGACY", "LDAP_DNS_LEGACY"),
					("LDAP_AUTH_OBJECT_CLASS", "LDAP_AUTH_OBJECT_CLASS"),
					("EXCLUDE_COMPUTER_ACCOUNTS", "EXCLUDE_COMPUTER_ACCOUNTS"),
					("LDAP_FIELD_MAP", "LDAP_FIELD_MAP"),
					(
						"LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN",
						"LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN",
					),
					(
						"LDAP_AUTH_CONNECTION_USER_DN",
						"LDAP_AUTH_CONNECTION_USER_DN",
					),
					(
						"LDAP_AUTH_CONNECTION_USERNAME",
						"LDAP_AUTH_CONNECTION_USERNAME",
					),
					(
						"LDAP_AUTH_CONNECTION_PASSWORD",
						"LDAP_AUTH_CONNECTION_PASSWORD",
					),
					("LDAP_AUTH_CONNECT_TIMEOUT", "LDAP_AUTH_CONNECT_TIMEOUT"),
					("LDAP_AUTH_RECEIVE_TIMEOUT", "LDAP_AUTH_RECEIVE_TIMEOUT"),
					("ADMIN_GROUP_TO_SEARCH", "ADMIN_GROUP_TO_SEARCH"),
				],
				max_length=128,
				verbose_name="name",
			),
		),
		migrations.AlterField(
			model_name="log",
			name="operation_type",
			field=models.CharField(
				choices=[
					("CREATE", "Create"),
					("READ", "Read"),
					("UPDATE", "Update"),
					("DELETE", "Delete"),
					("LOGIN", "Login"),
					("LOGOUT", "Logout"),
					("OPEN_LDAP_CONNECTION", "Open Connection"),
					("CLOSE_LDAP_CONNECTION", "Close Connection"),
					("RENAME", "Rename"),
					("MOVE", "Move"),
					("UNKNOWN", "Unknown"),
				],
				max_length=256,
				verbose_name="operation_type",
			),
		),
	]
