# Generated by Django 5.1.7 on 2025-07-14 17:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_ldap_ref"),
        ("core", "0004_ldap_objects_to_ldap_refs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicationsecuritygroup",
            name="ldap_objects",
        ),
    ]
