# Generated by Django 3.2 on 2022-07-31 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_log_willrotate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='willrotate',
        ),
        migrations.AddField(
            model_name='log',
            name='rotated',
            field=models.BooleanField(default=False, verbose_name='rotated'),
        ),
    ]
