# Generated by Django 3.2 on 2022-07-24 16:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220722_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='value_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), null=True, size=None),
        ),
        migrations.AddField(
            model_name='setting',
            name='value_bool',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='value_float',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='value_int',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=models.CharField(max_length=256, null=True, verbose_name='value'),
        ),
    ]
