# Generated by Django 3.2 on 2022-07-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220724_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='value_array',
        ),
        migrations.AddField(
            model_name='setting',
            name='value_json',
            field=models.JSONField(null=True),
        ),
    ]
