# Generated by Django 3.2 on 2022-07-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_log_objectclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
