# Generated by Django 3.2 on 2022-07-31 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_log_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='affectedObject',
            field=models.JSONField(blank=True, null=True, verbose_name='affectedObject'),
        ),
    ]
