# Generated by Django 3.2 on 2022-07-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220724_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(max_length=64, null=True, verbose_name='type'),
        ),
    ]
