# Generated by Django 4.2.4 on 2025-02-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_squashed_sso_rsa_others"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ldapsetting",
            name="name",
            field=models.CharField(
                choices=[
                    ("LDAP_AUTH_URL", "v_ldap_auth_url"),
                    ("LDAP_DOMAIN", "v_ldap_domain"),
                    ("LDAP_LOG_MAX", "v_ldap_log_max"),
                    ("LDAP_LOG_READ", "v_ldap_log_read"),
                    ("LDAP_LOG_CREATE", "v_ldap_log_create"),
                    ("LDAP_LOG_UPDATE", "v_ldap_log_update"),
                    ("LDAP_LOG_DELETE", "v_ldap_log_delete"),
                    ("LDAP_LOG_OPEN_CONNECTION", "v_ldap_log_open_connection"),
                    ("LDAP_LOG_CLOSE_CONNECTION", "v_ldap_log_close_connection"),
                    ("LDAP_LOG_LOGIN", "v_ldap_log_login"),
                    ("LDAP_LOG_LOGOUT", "v_ldap_log_logout"),
                    ("LDAP_AUTH_USE_SSL", "v_ldap_auth_use_ssl"),
                    ("LDAP_AUTH_USE_TLS", "v_ldap_auth_use_tls"),
                    ("LDAP_AUTH_TLS_VERSION", "v_ldap_auth_tls_version"),
                    ("LDAP_AUTH_SEARCH_BASE", "v_ldap_auth_search_base"),
                    ("LDAP_DNS_LEGACY", "v_ldap_dns_legacy"),
                    ("LDAP_AUTH_OBJECT_CLASS", "v_ldap_auth_object_class"),
                    ("EXCLUDE_COMPUTER_ACCOUNTS", "v_exclude_computer_accounts"),
                    ("LDAP_AUTH_USER_FIELDS", "v_ldap_auth_user_fields"),
                    ("LDAP_DIRTREE_OU_FILTER", "v_ldap_dirtree_ou_filter"),
                    ("LDAP_DIRTREE_CN_FILTER", "v_ldap_dirtree_cn_filter"),
                    (
                        "LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN",
                        "v_ldap_auth_active_directory_domain",
                    ),
                    ("LDAP_AUTH_CONNECTION_USER_DN", "v_ldap_auth_connection_user_dn"),
                    (
                        "LDAP_AUTH_CONNECTION_USERNAME",
                        "v_ldap_auth_connection_username",
                    ),
                    (
                        "LDAP_AUTH_CONNECTION_PASSWORD",
                        "v_ldap_auth_connection_password",
                    ),
                    ("LDAP_AUTH_CONNECT_TIMEOUT", "v_ldap_auth_connect_timeout"),
                    ("LDAP_AUTH_RECEIVE_TIMEOUT", "v_ldap_auth_receive_timeout"),
                    ("ADMIN_GROUP_TO_SEARCH", "v_admin_group_to_search"),
                ],
                max_length=128,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="ldapsetting",
            name="v_password_aes",
            field=models.BinaryField(blank=True, null=True, verbose_name="param_v_aes"),
        ),
        migrations.AlterField(
            model_name="ldapsetting",
            name="v_password_ct",
            field=models.BinaryField(blank=True, null=True, verbose_name="param_v_ct"),
        ),
        migrations.AlterField(
            model_name="ldapsetting",
            name="v_password_nonce",
            field=models.BinaryField(
                blank=True, null=True, verbose_name="param_v_nonce"
            ),
        ),
        migrations.AlterField(
            model_name="ldapsetting",
            name="v_password_tag",
            field=models.BinaryField(blank=True, null=True, verbose_name="param_v_tag"),
        ),
        migrations.AddConstraint(
            model_name="ldapsetting",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("v_password_aes", None),
                        ("v_password_ct", None),
                        ("v_password_nonce", None),
                        ("v_password_tag", None),
                    ),
                    models.Q(
                        ("v_password_aes__isnull", False),
                        ("v_password_ct__isnull", False),
                        ("v_password_nonce__isnull", False),
                        ("v_password_tag__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="v_password_crypt_data_all_or_none",
            ),
        ),
    ]
