# Generated by Django 3.2 on 2022-07-29 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
    ]
