# Generated by Django 4.2.4 on 2025-02-27 20:23

import core.models.application
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0009_remove_ldapsetting_lds_password_crypt_data_all_or_none_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                ("deleted", models.BooleanField(default=False, verbose_name="deleted")),
                ("notes", models.TextField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "client_id",
                    models.CharField(
                        default=core.models.application.generate_client_id,
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "client_secret",
                    models.CharField(
                        default=core.models.application.generate_client_secret,
                        max_length=255,
                    ),
                ),
                (
                    "redirect_uris",
                    models.TextField(help_text="Comma-separated redirect URIs"),
                ),
                ("scopes", models.TextField(default="openid profile email groups")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
