# Generated by Django 4.2.4 on 2025-02-28 01:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
    ]
