# Generated by Django 4.2.4 on 2025-03-04 18:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_application_enabled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="ldap_groups",
        ),
        migrations.AddField(
            model_name="application",
            name="groups",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(),
                default=list,
                size=None,
                verbose_name="Application Group Permissions",
            ),
        ),
    ]
