# Generated by Django 4.2.4 on 2025-03-05 15:59
from core.models.user import (
	User as UserModel,
	USER_TYPE_LDAP
)
from django.db import migrations, models, transaction
from core.utils.migrations import ignore_reverse

def set_user_type(apps, schema_editor):
	user: UserModel = apps.get_model('core', 'User')
	# Only apply on LDAP Users
	query_set = user.objects.exclude(dn__isnull=True).exclude(dn__exact='')
	with transaction.atomic():
		for obj in query_set:
			obj.user_type = USER_TYPE_LDAP
			obj.save()

class Migration(migrations.Migration):
	dependencies = [
		("core", "0013_remove_application_groups_applicationsecuritygroup"),
	]

	operations = [
		migrations.AddField(
			model_name="user",
			name="is_enabled",
			field=models.BooleanField(default=True),
		),
		migrations.AddField(
			model_name="user",
			name="user_type",
			field=models.CharField(
				choices=[("local", "Local User"), ("ldap", "LDAP User")],
				default="local",
				verbose_name="User Type",
			),
		),
		migrations.RunPython(set_user_type, ignore_reverse),
		migrations.RemoveField(
			model_name="user",
			name="is_local",
		),
	]
