# Generated by Django 4.2.4 on 2025-03-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_remove_user_is_local_user_is_enabled_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="ldap_password_aes",
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="ldap_password_ct",
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="ldap_password_nonce",
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="ldap_password_tag",
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
    ]
