# Generated by Django 4.2.4 on 2025-03-07 22:28

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    replaces = [
        ("core", "0016_remove_applicationsecuritygroup_name_and_more"),
        ("core", "0017_alter_applicationsecuritygroup_application"),
        ("core", "0018_alter_applicationsecuritygroup_ldap_objects_and_more"),
        ("core", "0019_alter_applicationsecuritygroup_users"),
    ]

    dependencies = [
        ("core", "0015_alter_user_ldap_password_aes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicationsecuritygroup",
            name="name",
        ),
        migrations.AlterField(
            model_name="applicationsecuritygroup",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.application",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="applicationsecuritygroup",
            name="application",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="core.application"
            ),
        ),
        migrations.AlterField(
            model_name="applicationsecuritygroup",
            name="ldap_objects",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="applicationsecuritygroup",
            name="users",
            field=models.ManyToManyField(
                blank=True, null=True, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="applicationsecuritygroup",
            name="users",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
