# Generated by Django 4.2.4 on 2025-03-07 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_alter_user_ldap_password_aes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicationsecuritygroup",
            name="name",
        ),
        migrations.AlterField(
            model_name="applicationsecuritygroup",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.application",
                unique=True,
            ),
        ),
    ]
