# Generated by Django 4.2.4 on 2025-03-07 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_remove_applicationsecuritygroup_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationsecuritygroup",
            name="application",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="core.application"
            ),
        ),
    ]
