# Generated by Django 4.2.4 on 2025-03-07 21:12

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_alter_applicationsecuritygroup_application"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationsecuritygroup",
            name="ldap_objects",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="applicationsecuritygroup",
            name="users",
            field=models.ManyToManyField(
                blank=True, null=True, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
