# Generated by Django 4.2.4 on 2025-03-07 22:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_alter_applicationsecuritygroup_ldap_objects_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationsecuritygroup",
            name="users",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
