# Generated by Django 4.2.4 on 2024-04-03 18:37

from django.db import migrations, transaction, models
from core.models.interlock_settings import (
	InterlockSetting,
	SETTING_KEY_LDAP_ENABLED,
	SETTING_KEY_TYPE_MAP
)

def create_settings(apps, schema_editor):
	ils: InterlockSetting = apps.get_model('core', 'InterlockSetting')
	with transaction.atomic():
		ils.objects.create(
			s_name=SETTING_KEY_LDAP_ENABLED,
			s_type=SETTING_KEY_TYPE_MAP[SETTING_KEY_LDAP_ENABLED],
			s_data_bool=False
		)

def delete_settings(apps, schema_editor):
	ils: InterlockSetting = apps.get_model('core', 'InterlockSetting')
	with transaction.atomic():
		ils.objects.delete(
			s_name=SETTING_KEY_LDAP_ENABLED,
			s_type=SETTING_KEY_TYPE_MAP[SETTING_KEY_LDAP_ENABLED]
		)

class Migration(migrations.Migration):

	dependencies = [
		('core', '0019_alter_applicationsecuritygroup_users'),
	]

	operations = [
		migrations.RunPython(create_settings, delete_settings),
        migrations.AlterField(
            model_name="interlocksetting",
            name="s_name",
            field=models.CharField(
                choices=[
                    ("AES_ENCRYPT_KEY", "ilck_aes_encrypt_key"),
                    ("FERNET_KEY", "ilck_fernet_key"),
                    ("LDAP_ENABLED", "ilck_ldap_enabled"),
                ],
                max_length=128,
                unique=True,
                verbose_name="name",
            ),
        ),
	]
