# Generated by Django 4.2.4 on 2025-03-11 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_add_interlock_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationsecuritygroup",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.application"
            ),
        ),
    ]
