################################################################################
#################### INTERLOCK IS LICENSED UNDER GNU AGPLv3 ####################
################## ORIGINAL PROJECT CREATED BY DYLAN BLANQUÉ ###################
########################## AND BR CONSULTING S.R.L. ############################
################################################################################
# Module: core.constants.attrs

# Global
LDAP_DATE_FORMAT = "%Y%m%d%H%M%S.%fZ"

LDAP_ESCAPE_REQUIRED_CHARS = (
	"+",
	";",
	",",
	"\\",
	"\"",
	"<",
	">",
	"#",
)

# LDAP Attributes
LDAP_ATTR_PASSWORD = "unicodePwd"
LDAP_ATTR_FIRST_NAME = "givenName"
LDAP_ATTR_LAST_NAME = "sn"
LDAP_ATTR_FULL_NAME = "displayName"
LDAP_ATTR_USERNAME_SAMBA_ADDS = "sAMAccountName"
LDAP_ATTR_EMAIL = "mail"
LDAP_ATTR_PHONE = "telephoneNumber"
LDAP_ATTR_ADDRESS = "streetAddress"
LDAP_ATTR_POSTAL_CODE = "postalCode"
LDAP_ATTR_CITY = "l"  # Local / City
LDAP_ATTR_STATE = "st"  # State/Province
LDAP_ATTR_COUNTRY = "co"
LDAP_ATTR_COUNTRY_DCC = "countryCode"
LDAP_ATTR_COUNTRY_ISO = "c"
LDAP_ATTR_WEBSITE = "wWWHomePage"
LDAP_ATTR_DN = "distinguishedName"
LDAP_ATTR_UPN = "userPrincipalName"
LDAP_ATTR_UAC = "userAccountControl"  # Permission ACLs
LDAP_ATTR_CREATED = "whenCreated"
LDAP_ATTR_MODIFIED = "whenChanged"
LDAP_ATTR_LAST_LOGIN = "lastLogon"
LDAP_ATTR_BAD_PWD_COUNT = "badPwdCount"
LDAP_ATTR_PWD_SET_AT = "pwdLastSet"
LDAP_ATTR_PRIMARY_GROUP_ID = "primaryGroupID"
LDAP_ATTR_OBJECT_CLASS = "objectClass"
LDAP_ATTR_OBJECT_CATEGORY = "objectCategory"
LDAP_ATTR_RELATIVE_ID = "objectRid"
LDAP_ATTR_SECURITY_ID = "objectSid"
LDAP_ATTR_GUID = "objectGUID"
LDAP_ATTR_ACCOUNT_TYPE = "sAMAccountType"
LDAP_ATTR_USER_GROUPS = "memberOf"
LDAP_ATTR_INITIALS = "initials"
LDAP_ATTR_COMMON_NAME = "cn"
LDAP_ATTR_GROUP_MEMBERS = "member"
LDAP_ATTR_GROUP_TYPE = "groupType"
LDAP_ATTR_LOGON_TIMESTAMP = "lastLogonTimestamp"
LDAP_ATTR_EXPIRES_AT = "accountExpires"

# LOCAL Attributes
LOCAL_USER_TYPE = "user_type"
LOCAL_ATTR_ID = "id"
LOCAL_ATTR_PATH = "path"
LOCAL_ATTR_USERTYPE = "user_type"
LOCAL_ATTR_USERNAME = "username"
LOCAL_ATTR_PASSWORD = "password"
LOCAL_ATTR_PASSWORD_CONFIRM = "password_confirm"
LOCAL_ATTR_FIRST_NAME = "first_name"
LOCAL_ATTR_LAST_NAME = "last_name"
LOCAL_ATTR_FULL_NAME = "full_name"
LOCAL_ATTR_INITIALS = "initials"
LOCAL_ATTR_PHONE = "phone"
LOCAL_ATTR_EMAIL = "email"
LOCAL_ATTR_DN = "distinguished_name"
LOCAL_ATTR_DN_SHORT = "dn"
LOCAL_ATTR_RELATIVE_ID = "object_relative_id"
LOCAL_ATTR_SECURITY_ID = "object_security_id"
LOCAL_ATTR_GUID = "object_guid"
LOCAL_ATTR_ADDRESS = "street_address"
LOCAL_ATTR_POSTAL_CODE = "postal_code"
LOCAL_ATTR_CITY = "city"
LOCAL_ATTR_STATE = "state_province"
LOCAL_ATTR_COUNTRY = "country_name"
LOCAL_ATTR_COUNTRY_DCC = "country_code_dcc"
LOCAL_ATTR_COUNTRY_ISO = "country_code_iso"
LOCAL_ATTR_WEBSITE = "website"
LOCAL_ATTR_UPN = "user_principal_name"
LOCAL_ATTR_UAC = "user_account_control"
LOCAL_ATTR_PERMISSIONS = "permissions"
LOCAL_ATTR_CREATED = "created_at"
LOCAL_ATTR_MODIFIED = "modified_at"
LOCAL_ATTR_LAST_LOGIN = "last_login_win32"
LOCAL_ATTR_LOGON_TIMESTAMP = "login_timestamp"
LOCAL_ATTR_BAD_PWD_COUNT = "bad_password_count"
LOCAL_ATTR_PWD_SET_AT = "password_set_at"
LOCAL_ATTR_PRIMARY_GROUP_ID = "primary_group_id"
LOCAL_ATTR_OBJECT_CLASS = "object_class"
LOCAL_ATTR_OBJECT_CATEGORY = "object_category"
LOCAL_ATTR_ACCOUNT_TYPE = "account_type"
LOCAL_ATTR_USER_GROUPS = "groups"
LOCAL_ATTR_GROUP_MEMBERS = "members"
LOCAL_ATTR_GROUP_TYPE = "group_types"
LOCAL_ATTR_GROUP_SCOPE = "group_scopes"
LOCAL_ATTR_IS_ENABLED = "is_enabled"
LOCAL_ATTR_TYPE = "type"
LOCAL_ATTR_NAME = "name"
LOCAL_ATTR_BUILT_IN = "builtin"
LOCAL_ATTR_EXPIRES_AT = "expires_at"
LOCAL_ATTR_USER_ADD_GROUPS = "groups_to_add"
LOCAL_ATTR_USER_RM_GROUPS = "groups_to_remove"
LOCAL_ATTR_GROUP_HAS_MEMBERS = "has_members"
LOCAL_ATTR_GROUP_ADD_MEMBERS = "members_to_add"
LOCAL_ATTR_GROUP_RM_MEMBERS = "members_to_remove"

LOCAL_ATTRS_MAP = {
	LOCAL_ATTR_DN: LDAP_ATTR_DN,
	LOCAL_ATTR_USERNAME: LDAP_ATTR_USERNAME_SAMBA_ADDS,
	LOCAL_ATTR_EMAIL: LDAP_ATTR_EMAIL,
	LOCAL_ATTR_PASSWORD: LDAP_ATTR_PASSWORD,
	LOCAL_ATTR_FIRST_NAME: LDAP_ATTR_FIRST_NAME,
	LOCAL_ATTR_LAST_NAME: LDAP_ATTR_LAST_NAME,
	LOCAL_ATTR_FULL_NAME: LDAP_ATTR_FULL_NAME,
	LOCAL_ATTR_INITIALS: LDAP_ATTR_INITIALS,
	LOCAL_ATTR_PHONE: LDAP_ATTR_PHONE,
	LOCAL_ATTR_ADDRESS: LDAP_ATTR_ADDRESS,
	LOCAL_ATTR_POSTAL_CODE: LDAP_ATTR_POSTAL_CODE,
	LOCAL_ATTR_CITY: LDAP_ATTR_CITY,
	LOCAL_ATTR_STATE: LDAP_ATTR_STATE,
	LOCAL_ATTR_COUNTRY: LDAP_ATTR_COUNTRY,
	LOCAL_ATTR_COUNTRY_DCC: LDAP_ATTR_COUNTRY_DCC,
	LOCAL_ATTR_COUNTRY_ISO: LDAP_ATTR_COUNTRY_ISO,
	LOCAL_ATTR_WEBSITE: LDAP_ATTR_WEBSITE,
	LOCAL_ATTR_UPN: LDAP_ATTR_UPN,
	LOCAL_ATTR_UAC: LDAP_ATTR_UAC,
	LOCAL_ATTR_CREATED: LDAP_ATTR_CREATED,
	LOCAL_ATTR_MODIFIED: LDAP_ATTR_MODIFIED,
	LOCAL_ATTR_LAST_LOGIN: LDAP_ATTR_LAST_LOGIN,
	LOCAL_ATTR_BAD_PWD_COUNT: LDAP_ATTR_BAD_PWD_COUNT,
	LOCAL_ATTR_PWD_SET_AT: LDAP_ATTR_PWD_SET_AT,
	LOCAL_ATTR_PRIMARY_GROUP_ID: LDAP_ATTR_PRIMARY_GROUP_ID,
	LOCAL_ATTR_OBJECT_CLASS: LDAP_ATTR_OBJECT_CLASS,
	LOCAL_ATTR_OBJECT_CATEGORY: LDAP_ATTR_OBJECT_CATEGORY,
	LOCAL_ATTR_RELATIVE_ID: LDAP_ATTR_RELATIVE_ID,
	LOCAL_ATTR_SECURITY_ID: LDAP_ATTR_SECURITY_ID,
	LOCAL_ATTR_ACCOUNT_TYPE: LDAP_ATTR_ACCOUNT_TYPE,
	LOCAL_ATTR_USER_GROUPS: LDAP_ATTR_USER_GROUPS,
	LOCAL_ATTR_GROUP_MEMBERS: LDAP_ATTR_GROUP_MEMBERS,
	LOCAL_ATTR_LOGON_TIMESTAMP: LDAP_ATTR_LOGON_TIMESTAMP,
	LOCAL_ATTR_EXPIRES_AT: LDAP_ATTR_EXPIRES_AT,
	LOCAL_ATTR_NAME: LDAP_ATTR_COMMON_NAME,
	LOCAL_ATTR_GROUP_TYPE: LDAP_ATTR_GROUP_TYPE,
}
