################################################################################
#################### INTERLOCK IS LICENSED UNDER GNU AGPLv3 ####################
################## ORIGINAL PROJECT CREATED BY DYLAN BLANQUÉ ###################
########################## AND BR CONSULTING S.R.L. ############################
################################################################################
# Module: core.constants.settings
# Contains constants for LDAP Setting Keys
################################################################################

K_LDAP_AUTH_URL = "LDAP_AUTH_URL"
K_LDAP_DOMAIN = "LDAP_DOMAIN"
K_LDAP_AUTH_USE_SSL = "LDAP_AUTH_USE_SSL"
K_LDAP_AUTH_USE_TLS = "LDAP_AUTH_USE_TLS"
K_LDAP_AUTH_TLS_VERSION = "LDAP_AUTH_TLS_VERSION"
K_LDAP_AUTH_SEARCH_BASE = "LDAP_AUTH_SEARCH_BASE"
K_LDAP_DNS_LEGACY = "LDAP_DNS_LEGACY"
K_LDAP_AUTH_OBJECT_CLASS = "LDAP_AUTH_OBJECT_CLASS"
K_EXCLUDE_COMPUTER_ACCOUNTS = "EXCLUDE_COMPUTER_ACCOUNTS"
K_LDAP_FIELD_MAP = "LDAP_FIELD_MAP"
K_LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN = "LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN"
K_LDAP_AUTH_CONNECTION_USER_DN = "LDAP_AUTH_CONNECTION_USER_DN"
K_LDAP_AUTH_CONNECTION_USERNAME = "LDAP_AUTH_CONNECTION_USERNAME"
K_LDAP_AUTH_CONNECTION_PASSWORD = "LDAP_AUTH_CONNECTION_PASSWORD"
K_LDAP_AUTH_CONNECT_TIMEOUT = "LDAP_AUTH_CONNECT_TIMEOUT"
K_LDAP_AUTH_RECEIVE_TIMEOUT = "LDAP_AUTH_RECEIVE_TIMEOUT"
K_ADMIN_GROUP_TO_SEARCH = "ADMIN_GROUP_TO_SEARCH"
