################################################################################
#################### INTERLOCK IS LICENSED UNDER GNU AGPLv3 ####################
################## ORIGINAL PROJECT CREATED BY DYLAN BLANQUÉ ###################
########################## AND BR CONSULTING S.R.L. ############################
################################################################################
# Module: interlock_backend.ldap.countries
# ISO 3166-1 Countries
# Source: https://ldapwiki.com/wiki/Wiki.jsp?page=Country%20Code
# Transcription / Conversion by Dylan Blanqué
################################################################################

LDAP_COUNTRIES = {
	"Afghanistan": {"isoCode": "AF", "dccCode": "4"},
	"Albania": {"isoCode": "AL", "dccCode": "8"},
	"Algeria": {"isoCode": "DZ", "dccCode": "12"},
	"American Samoa": {"isoCode": "AS", "dccCode": "16"},
	"Andorra": {"isoCode": "AD", "dccCode": "20"},
	"Angola": {"isoCode": "AO", "dccCode": "24"},
	"Anguilla": {"isoCode": "AI", "dccCode": "660"},
	"Antarctica": {"isoCode": "AQ", "dccCode": "10"},
	"Antigua and Barbuda": {"isoCode": "AG", "dccCode": "28"},
	"Argentina": {"isoCode": "AR", "dccCode": "32"},
	"Armenia": {"isoCode": "AM", "dccCode": "51"},
	"Aruba": {"isoCode": "AW", "dccCode": "533"},
	"Australia": {"isoCode": "AU", "dccCode": "36"},
	"Austria": {"isoCode": "AT", "dccCode": "40"},
	"Azerbaijan": {"isoCode": "AZ", "dccCode": "31"},
	"Bahamas": {"isoCode": "BS", "dccCode": "44"},
	"Bahrain": {"isoCode": "BH", "dccCode": "48"},
	"Bangladesh": {"isoCode": "BD", "dccCode": "50"},
	"Barbados": {"isoCode": "BB", "dccCode": "52"},
	"Belarus": {"isoCode": "BY", "dccCode": "112"},
	"Belgium": {"isoCode": "BE", "dccCode": "56"},
	"Belize": {"isoCode": "BZ", "dccCode": "84"},
	"Benin": {"isoCode": "BJ", "dccCode": "204"},
	"Bermuda": {"isoCode": "BM", "dccCode": "60"},
	"Bhutan": {"isoCode": "BT", "dccCode": "64"},
	"Bolivia": {"isoCode": "BO", "dccCode": "68"},
	"Bonaire": {"isoCode": "BQ", "dccCode": "535"},
	"Bosnia and Herzegovina": {"isoCode": "BA", "dccCode": "70"},
	"Botswana": {"isoCode": "BW", "dccCode": "72"},
	"Bouvet Island": {"isoCode": "BV", "dccCode": "74"},
	"Brazil": {"isoCode": "BR", "dccCode": "76"},
	"British Indian Ocean Territory": {"isoCode": "IO", "dccCode": "86"},
	"Brunei Darussalam": {"isoCode": "BN", "dccCode": "96"},
	"Bulgaria": {"isoCode": "BG", "dccCode": "100"},
	"Burkina Faso": {"isoCode": "BF", "dccCode": "854"},
	"Burundi": {"isoCode": "BI", "dccCode": "108"},
	"Cambodia": {"isoCode": "KH", "dccCode": "116"},
	"Cameroon": {"isoCode": "CM", "dccCode": "120"},
	"Canada": {"isoCode": "CA", "dccCode": "124"},
	"Cape Verde": {"isoCode": "CV", "dccCode": "132"},
	"Cayman Islands": {"isoCode": "KY", "dccCode": "136"},
	"Central African Republic": {"isoCode": "CF", "dccCode": "140"},
	"Chad": {"isoCode": "TD", "dccCode": "148"},
	"Chile": {"isoCode": "CL", "dccCode": "152"},
	"China": {"isoCode": "CN", "dccCode": "156"},
	"Christmas Island": {"isoCode": "CX", "dccCode": "162"},
	"Cocos (Keeling) Islands": {"isoCode": "CC", "dccCode": "166"},
	"Colombia": {"isoCode": "CO", "dccCode": "170"},
	"Comoros": {"isoCode": "KM", "dccCode": "174"},
	"Congo": {"isoCode": "CG", "dccCode": "178"},
	"Democratic Republic of the Congo": {"isoCode": "CD", "dccCode": "180"},
	"Cook Islands": {"isoCode": "CK", "dccCode": "184"},
	"Costa Rica": {"isoCode": "CR", "dccCode": "188"},
	"Croatia": {"isoCode": "HR", "dccCode": "191"},
	"Cuba": {"isoCode": "CU", "dccCode": "192"},
	"Curacao": {"isoCode": "CW", "dccCode": "531"},
	"Cyprus": {"isoCode": "CY", "dccCode": "196"},
	"Czech Republic": {"isoCode": "CZ", "dccCode": "203"},
	"Cote d'Ivoire": {"isoCode": "CI", "dccCode": "384"},
	"Denmark": {"isoCode": "DK", "dccCode": "208"},
	"Djibouti": {"isoCode": "DJ", "dccCode": "262"},
	"Dominica": {"isoCode": "DM", "dccCode": "212"},
	"Dominican Republic": {"isoCode": "DO", "dccCode": "214"},
	"Ecuador": {"isoCode": "EC", "dccCode": "218"},
	"Egypt": {"isoCode": "EG", "dccCode": "818"},
	"El Salvador": {"isoCode": "SV", "dccCode": "222"},
	"Equatorial Guinea": {"isoCode": "GQ", "dccCode": "226"},
	"Eritrea": {"isoCode": "ER", "dccCode": "232"},
	"Estonia": {"isoCode": "EE", "dccCode": "233"},
	"Ethiopia": {"isoCode": "ET", "dccCode": "231"},
	"Islas Malvinas": {"isoCode": "FK", "dccCode": "238"},
	"Faroe Islands": {"isoCode": "FO", "dccCode": "234"},
	"Fiji": {"isoCode": "FJ", "dccCode": "242"},
	"Finland": {"isoCode": "FI", "dccCode": "246"},
	"France": {"isoCode": "FR", "dccCode": "250"},
	"French Guiana": {"isoCode": "GF", "dccCode": "254"},
	"French Polynesia": {"isoCode": "PF", "dccCode": "258"},
	"French Southern Territories": {"isoCode": "TF", "dccCode": "260"},
	"Gabon": {"isoCode": "GA", "dccCode": "266"},
	"Gambia": {"isoCode": "GM", "dccCode": "270"},
	"Georgia": {"isoCode": "GE", "dccCode": "268"},
	"Germany": {"isoCode": "DE", "dccCode": "276"},
	"Ghana": {"isoCode": "GH", "dccCode": "288"},
	"Gibraltar": {"isoCode": "GI", "dccCode": "292"},
	"Greece": {"isoCode": "GR", "dccCode": "300"},
	"Greenland": {"isoCode": "GL", "dccCode": "304"},
	"Grenada": {"isoCode": "GD", "dccCode": "308"},
	"Guadeloupe": {"isoCode": "GP", "dccCode": "312"},
	"Guam": {"isoCode": "GU", "dccCode": "316"},
	"Guatemala": {"isoCode": "GT", "dccCode": "320"},
	"Guernsey": {"isoCode": "GG", "dccCode": "831"},
	"Guinea": {"isoCode": "GN", "dccCode": "324"},
	"Guinea-Bissau": {"isoCode": "GW", "dccCode": "624"},
	"Guyana": {"isoCode": "GY", "dccCode": "328"},
	"Haiti": {"isoCode": "HT", "dccCode": "332"},
	"Heard Island and McDonald Islands": {"isoCode": "HM", "dccCode": "334"},
	"Holy See (Vatican City State)": {"isoCode": "VA", "dccCode": "336"},
	"Honduras": {"isoCode": "HN", "dccCode": "340"},
	"Hong Kong": {"isoCode": "HK", "dccCode": "344"},
	"Hungary": {"isoCode": "HU", "dccCode": "348"},
	"Iceland": {"isoCode": "IS", "dccCode": "352"},
	"India": {"isoCode": "IN", "dccCode": "356"},
	"Indonesia": {"isoCode": "ID", "dccCode": "360"},
	"Islamic Republic of Iran": {"isoCode": "IR", "dccCode": "364"},
	"Iraq": {"isoCode": "IQ", "dccCode": "368"},
	"Ireland": {"isoCode": "IE", "dccCode": "372"},
	"Isle of Man": {"isoCode": "IM", "dccCode": "833"},
	"Israel": {"isoCode": "IL", "dccCode": "376"},
	"Italy": {"isoCode": "IT", "dccCode": "380"},
	"Jamaica": {"isoCode": "JM", "dccCode": "388"},
	"Japan": {"isoCode": "JP", "dccCode": "392"},
	"Jersey": {"isoCode": "JE", "dccCode": "832"},
	"Jordan": {"isoCode": "JO", "dccCode": "400"},
	"Kazakhstan": {"isoCode": "KZ", "dccCode": "398"},
	"Kenya": {"isoCode": "KE", "dccCode": "404"},
	"Kiribati": {"isoCode": "KI", "dccCode": "296"},
	"Democratic People's Republic of Korea": {
		"isoCode": "KR",
		"dccCode": "410",
	},
	"Kuwait": {"isoCode": "KW", "dccCode": "414"},
	"Kyrgyzstan": {"isoCode": "KG", "dccCode": "417"},
	"Lao People's Democratic Republic": {"isoCode": "LA", "dccCode": "418"},
	"Latvia": {"isoCode": "LV", "dccCode": "428"},
	"Lebanon": {"isoCode": "LB", "dccCode": "422"},
	"Lesotho": {"isoCode": "LS", "dccCode": "426"},
	"Liberia": {"isoCode": "LR", "dccCode": "430"},
	"Libya": {"isoCode": "LY", "dccCode": "434"},
	"Liechtenstein": {"isoCode": "LI", "dccCode": "438"},
	"Lithuania": {"isoCode": "LT", "dccCode": "440"},
	"Luxembourg": {"isoCode": "LU", "dccCode": "442"},
	"Macao": {"isoCode": "MO", "dccCode": "446"},
	"Former Yugoslav Republic of Macedonia": {
		"isoCode": "MK",
		"dccCode": "807",
	},
	"Madagascar": {"isoCode": "MG", "dccCode": "450"},
	"Malawi": {"isoCode": "MW", "dccCode": "454"},
	"Malaysia": {"isoCode": "MY", "dccCode": "458"},
	"Maldives": {"isoCode": "MV", "dccCode": "462"},
	"Mali": {"isoCode": "ML", "dccCode": "466"},
	"Malta": {"isoCode": "MT", "dccCode": "470"},
	"Marshall Islands": {"isoCode": "MH", "dccCode": "584"},
	"Martinique": {"isoCode": "MQ", "dccCode": "474"},
	"Mauritania": {"isoCode": "MR", "dccCode": "478"},
	"Mauritius": {"isoCode": "MU", "dccCode": "480"},
	"Mayotte": {"isoCode": "YT", "dccCode": "175"},
	"Mexico": {"isoCode": "MX", "dccCode": "484"},
	"Federated States of Micronesia": {"isoCode": "FM", "dccCode": "583"},
	"Republic of Moldova": {"isoCode": "MD", "dccCode": "498"},
	"Monaco": {"isoCode": "MC", "dccCode": "492"},
	"Mongolia": {"isoCode": "MN", "dccCode": "496"},
	"Montenegro": {"isoCode": "ME", "dccCode": "499"},
	"Montserrat": {"isoCode": "MS", "dccCode": "500"},
	"Morocco": {"isoCode": "MA", "dccCode": "504"},
	"Mozambique": {"isoCode": "MZ", "dccCode": "508"},
	"Myanmar": {"isoCode": "MM", "dccCode": "104"},
	"Namibia": {"isoCode": "NA", "dccCode": "516"},
	"Nauru": {"isoCode": "NR", "dccCode": "520"},
	"Nepal": {"isoCode": "NP", "dccCode": "524"},
	"Netherlands": {"isoCode": "NL", "dccCode": "528"},
	"New Caledonia": {"isoCode": "NC", "dccCode": "687"},
	"New Zealand": {"isoCode": "NZ", "dccCode": "554"},
	"Nicaragua": {"isoCode": "NI", "dccCode": "558"},
	"Niger": {"isoCode": "NE", "dccCode": "562"},
	"Nigeria": {"isoCode": "NG", "dccCode": "566"},
	"Niue": {"isoCode": "NU", "dccCode": "570"},
	"Norfolk Island": {"isoCode": "NF", "dccCode": "574"},
	"Northern Mariana Islands": {"isoCode": "MP", "dccCode": "580"},
	"Norway": {"isoCode": "NO", "dccCode": "578"},
	"Oman": {"isoCode": "OM", "dccCode": "512"},
	"Pakistan": {"isoCode": "PK", "dccCode": "586"},
	"Palau": {"isoCode": "PW", "dccCode": "585"},
	"State of Palestine": {"isoCode": "PS", "dccCode": "275"},
	"Panama": {"isoCode": "PA", "dccCode": "591"},
	"Papua New Guinea": {"isoCode": "PG", "dccCode": "598"},
	"Paraguay": {"isoCode": "PY", "dccCode": "600"},
	"Peru": {"isoCode": "PE", "dccCode": "604"},
	"Philippines": {"isoCode": "PH", "dccCode": "608"},
	"Pitcairn": {"isoCode": "PN", "dccCode": "612"},
	"Poland": {"isoCode": "PL", "dccCode": "616"},
	"Portugal": {"isoCode": "PT", "dccCode": "620"},
	"Puerto Rico": {"isoCode": "PR", "dccCode": "630"},
	"Qatar": {"isoCode": "QA", "dccCode": "634"},
	"Romania": {"isoCode": "RO", "dccCode": "642"},
	"Russian Federation": {"isoCode": "RU", "dccCode": "643"},
	"Rwanda": {"isoCode": "RW", "dccCode": "646"},
	"Reunion": {"isoCode": "RE", "dccCode": "638"},
	"Saint Barthelemy": {"isoCode": "BL", "dccCode": "652"},
	"Saint Helena": {"isoCode": "SH", "dccCode": "654"},
	"Saint Kitts and Nevis": {"isoCode": "KN", "dccCode": "659"},
	"Saint Lucia": {"isoCode": "LC", "dccCode": "662"},
	"Saint Martin (French part)": {"isoCode": "MF", "dccCode": "663"},
	"Saint Pierre and Miquelon": {"isoCode": "PM", "dccCode": "666"},
	"Saint Vincent and the Grenadines": {"isoCode": "VC", "dccCode": "670"},
	"Samoa": {"isoCode": "WS", "dccCode": "882"},
	"San Marino": {"isoCode": "SM", "dccCode": "674"},
	"Sao Tome and Principe": {"isoCode": "ST", "dccCode": "678"},
	"Saudi Arabia": {"isoCode": "SA", "dccCode": "682"},
	"Senegal": {"isoCode": "SN", "dccCode": "686"},
	"Serbia": {"isoCode": "RS", "dccCode": "688"},
	"Seychelles": {"isoCode": "SC", "dccCode": "690"},
	"Sierra Leone": {"isoCode": "SL", "dccCode": "694"},
	"Singapore": {"isoCode": "SG", "dccCode": "702"},
	"Sint Maarten (Dutch part)": {"isoCode": "SX", "dccCode": "534"},
	"Slovakia": {"isoCode": "SK", "dccCode": "703"},
	"Slovenia": {"isoCode": "SI", "dccCode": "386"},
	"Solomon Islands": {"isoCode": "SB", "dccCode": "90"},
	"Somalia": {"isoCode": "SO", "dccCode": "706"},
	"South Africa": {"isoCode": "ZA", "dccCode": "710"},
	"South Georgia and the South Sandwich Islands": {
		"isoCode": "GS",
		"dccCode": "239",
	},
	"South Sudan": {"isoCode": "SS", "dccCode": "728"},
	"Spain": {"isoCode": "ES", "dccCode": "724"},
	"Sri Lanka": {"isoCode": "LK", "dccCode": "144"},
	"Sudan": {"isoCode": "SD", "dccCode": "729"},
	"Suriname": {"isoCode": "SR", "dccCode": "740"},
	"Svalbard and Jan Mayen": {"isoCode": "SJ", "dccCode": "744"},
	"Swaziland": {"isoCode": "SZ", "dccCode": "748"},
	"Sweden": {"isoCode": "SE", "dccCode": "752"},
	"Switzerland": {"isoCode": "CH", "dccCode": "756"},
	"Syrian Arab Republic": {"isoCode": "SY", "dccCode": "760"},
	"Taiwan, Province of China": {"isoCode": "TW", "dccCode": "158"},
	"Tajikistan": {"isoCode": "TJ", "dccCode": "762"},
	"United Republic of Tanzania": {"isoCode": "TZ", "dccCode": "834"},
	"Thailand": {"isoCode": "TH", "dccCode": "764"},
	"Timor-Leste": {"isoCode": "TL", "dccCode": "626"},
	"Togo": {"isoCode": "TG", "dccCode": "768"},
	"Tokelau": {"isoCode": "TK", "dccCode": "772"},
	"Tonga": {"isoCode": "TO", "dccCode": "776"},
	"Trinidad and Tobago": {"isoCode": "TT", "dccCode": "780"},
	"Tunisia": {"isoCode": "TN", "dccCode": "788"},
	"Turkey": {"isoCode": "TR", "dccCode": "792"},
	"Turkmenistan": {"isoCode": "TM", "dccCode": "795"},
	"Turks and Caicos Islands": {"isoCode": "TC", "dccCode": "796"},
	"Tuvalu": {"isoCode": "TV", "dccCode": "798"},
	"Uganda": {"isoCode": "UG", "dccCode": "800"},
	"Ukraine": {"isoCode": "UA", "dccCode": "804"},
	"United Arab Emirates": {"isoCode": "AE", "dccCode": "784"},
	"United Kingdom": {"isoCode": "GB", "dccCode": "826"},
	"United States": {"isoCode": "US", "dccCode": "840"},
	"United States Minor Outlying Islands": {"isoCode": "UM", "dccCode": "581"},
	"Uruguay": {"isoCode": "UY", "dccCode": "858"},
	"Uzbekistan": {"isoCode": "UZ", "dccCode": "860"},
	"Vanuatu": {"isoCode": "VU", "dccCode": "548"},
	"Venezuela": {"isoCode": "VE", "dccCode": "862"},
	"Vietnam": {"isoCode": "VN", "dccCode": "704"},
	"British Virgin Islands": {"isoCode": "VG", "dccCode": "92"},
	"US Virgin Islands": {"isoCode": "VI", "dccCode": "850"},
	"Wallis and Futuna": {"isoCode": "WF", "dccCode": "876"},
	"Western Sahara": {"isoCode": "EH", "dccCode": "732"},
	"Yemen": {"isoCode": "YE", "dccCode": "887"},
	"Zambia": {"isoCode": "ZM", "dccCode": "894"},
	"Zimbabwe": {"isoCode": "ZW", "dccCode": "716"},
}
