# LOG CLASS CHOICES

LOG_TARGET_ALL = "ALL"

LOG_PARAM_UNKNOWN = "UNKNOWN"
LOG_PARAM_OTHER = "OTHER"
LOG_ACTION_CREATE = "CREATE"
LOG_ACTION_READ = "READ"
LOG_ACTION_UPDATE = "UPDATE"
LOG_ACTION_DELETE = "DELETE"
LOG_ACTION_MOVE = "MOVE"
LOG_ACTION_RENAME = "RENAME"
LOG_ACTION_LOGIN = "LOGIN"
LOG_ACTION_LOGOUT = "LOGOUT"
LOG_ACTION_OPEN = "OPEN_LDAP_CONNECTION"
LOG_ACTION_CLOSE = "CLOSE_LDAP_CONNECTION"
ACTION_CHOICES = [
	(LOG_ACTION_CREATE, "Create"),
	(LOG_ACTION_READ, "Read"),
	(LOG_ACTION_UPDATE, "Update"),
	(LOG_ACTION_DELETE, "Delete"),
	(LOG_ACTION_LOGIN, "Login"),
	(LOG_ACTION_LOGOUT, "Logout"),
	(LOG_ACTION_OPEN, "Open Connection"),
	(LOG_ACTION_CLOSE, "Close Connection"),
	(LOG_ACTION_RENAME, "Rename"),
	(LOG_ACTION_MOVE, "Move"),
	(LOG_PARAM_UNKNOWN, "Unknown"),
]

LOG_CLASS_USER = "USER"
LOG_CLASS_GROUP = "GROUP"
LOG_CLASS_OU = "OU"
LOG_CLASS_DOM = "DOM"
LOG_CLASS_GPO = "GPO"
LOG_CLASS_LDAP = "LDAP"
LOG_CLASS_CONN = "CONN"
LOG_CLASS_SET = "SET"
LOG_CLASS_DNSZ = "DNSZ"
LOG_CLASS_DNSR = "DNSR"
LOG_CLASS_APP = "SSO_APP"
LOG_CLASS_APP_GROUP = "SSO_ASG"
LOG_CLASS_CLIENT = "SSO_CLIENT"
CLASS_CHOICES = [
	(LOG_CLASS_USER, "User"),
	(LOG_CLASS_GROUP, "Group"),
	(LOG_CLASS_APP, "SSO Application"),
	(LOG_CLASS_CLIENT, "SSO Client"),
	(LOG_CLASS_APP_GROUP, "SSO Application Group"),
	(LOG_CLASS_OU, "Organizational Unit"),
	(LOG_CLASS_DOM, "Domain"),
	(LOG_CLASS_GPO, "Group Policy Object"),
	(LOG_CLASS_LDAP, "LDAP Object"),
	(LOG_CLASS_CONN, "Connection"),
	(LOG_CLASS_SET, "Setting"),
	(LOG_CLASS_DNSZ, "DNS Zone"),
	(LOG_CLASS_DNSR, "DNS Record"),
	(LOG_PARAM_UNKNOWN, "Unknown"),
]

LOG_EXTRA_TOTP_CREATE = "TOTP_CREATE"
LOG_EXTRA_TOTP_VALIDATE = "TOTP_VALIDATE"
LOG_EXTRA_TOTP_DELETE = "TOTP_DELETE"
LOG_EXTRA_USER_END_USER_UPDATE = "END_USER_UPDATED"
LOG_EXTRA_USER_CHANGE_PASSWORD = "CHANGED_PASSWORD"
LOG_EXTRA_ENABLE = "ENABLE"
LOG_EXTRA_DISABLE = "DISABLE"
LOG_EXTRA_UNLOCK = "UNLOCK"
LOG_EXTRA_EXPORT = "EXPORT"
