################################################################################
#################### INTERLOCK IS LICENSED UNDER GNU AGPLv3 ####################
################## ORIGINAL PROJECT CREATED BY DYLAN BLANQUÉ ###################
########################## AND BR CONSULTING S.R.L. ############################
################################################################################
# Module: core.constants.attrs.local

LOCAL_ATTR_ID = "id"
LOCAL_ATTR_VALUE = "value"
LOCAL_ATTR_PATH = "path"
LOCAL_ATTR_USERTYPE = "user_type"
LOCAL_ATTR_USERNAME = "username"
LOCAL_ATTR_PASSWORD = "password"
LOCAL_ATTR_PASSWORD_CONFIRM = "password_confirm"
LOCAL_ATTR_FIRST_NAME = "first_name"
LOCAL_ATTR_LAST_NAME = "last_name"
LOCAL_ATTR_FULL_NAME = "full_name"
LOCAL_ATTR_INITIALS = "initials"
LOCAL_ATTR_PHONE = "phone"
LOCAL_ATTR_EMAIL = "email"
LOCAL_ATTR_DN = "distinguished_name"
LOCAL_ATTR_DN_SHORT = "dn"
LOCAL_ATTR_RELATIVE_ID = "object_relative_id"
LOCAL_ATTR_SECURITY_ID = "object_security_id"
LOCAL_ATTR_GUID = "object_guid"
LOCAL_ATTR_ADDRESS = "street_address"
LOCAL_ATTR_POSTAL_CODE = "postal_code"
LOCAL_ATTR_CITY = "city"
LOCAL_ATTR_STATE = "state_province"
LOCAL_ATTR_COUNTRY = "country_name"
LOCAL_ATTR_COUNTRY_DCC = "country_code_dcc"
LOCAL_ATTR_COUNTRY_ISO = "country_code_iso"
LOCAL_ATTR_WEBSITE = "website"
LOCAL_ATTR_UPN = "user_principal_name"
LOCAL_ATTR_UAC = "user_account_control"
LOCAL_ATTR_PERMISSIONS = "permissions"
LOCAL_ATTR_CREATED = "created_at"
LOCAL_ATTR_MODIFIED = "modified_at"
LOCAL_ATTR_LAST_LOGIN = "last_login"
LOCAL_ATTR_LAST_LOGIN_WIN32 = "last_login_win32"
LOCAL_ATTR_LOGON_TIMESTAMP = "login_timestamp"
LOCAL_ATTR_BAD_PWD_COUNT = "bad_password_count"
LOCAL_ATTR_PWD_SET_AT = "password_set_at"
LOCAL_ATTR_PRIMARY_GROUP_ID = "primary_group_id"
LOCAL_ATTR_OBJECT_CLASS = "object_class"
LOCAL_ATTR_OBJECT_CATEGORY = "object_category"
LOCAL_ATTR_ACCOUNT_TYPE = "account_type"
LOCAL_ATTR_USER_GROUPS = "groups"
LOCAL_ATTR_GROUP_MEMBERS = "members"
LOCAL_ATTR_GROUP_TYPE = "group_types"
LOCAL_ATTR_GROUP_SCOPE = "group_scopes"
LOCAL_ATTR_IS_ENABLED = "is_enabled"
LOCAL_ATTR_TYPE = "type"
LOCAL_ATTR_NAME = "name"
LOCAL_ATTR_BUILT_IN = "builtin"
LOCAL_ATTR_EXPIRES_AT = "expires_at"
LOCAL_ATTR_USER_ADD_GROUPS = "groups_to_add"
LOCAL_ATTR_USER_RM_GROUPS = "groups_to_remove"
LOCAL_ATTR_GROUP_HAS_MEMBERS = "has_members"
LOCAL_ATTR_GROUP_ADD_MEMBERS = "members_to_add"
LOCAL_ATTR_GROUP_RM_MEMBERS = "members_to_remove"
